# Generated by Django 5.0.6 on 2024-07-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('phone_number', models.CharField(max_length=13)),
                ('telegram_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('travel_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('eating', models.IntegerField()),
                ('viza', models.BooleanField()),
                ('medical_care', models.CharField(max_length=5)),
                ('experience', models.CharField(max_length=100)),
                ('water_zam_zam', models.IntegerField()),
            ],
        ),
    ]
