# Generated by Django 5.0.6 on 2024-07-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='price',
            field=models.IntegerField(default=1050),
            preserve_default=False,
        ),
    ]
